### ISSUE TITLE
Publish releases to npm

### ISSUE THREAD

**Issue by olle** [Contargo/flyps#29]
Hi! If you register and join the organization `contargo` at npmjs.com, a packaged release can be easily published to npm via the Make target `make publish` or npm task `npm publish`.

It's required that the `package.json` is manually maintained and updated as versions are packaged and prepared for releases.

**Comment by fheft** [comment]
Thanks for the information!

Could you please add me to the `contargo` org at npmjs? I haven't found a way to join by myself.
My username on npmjs is [florianh](https://www.npmjs.com/~florianh).

**Comment by olle** [comment]
I've sent an maintainer _invite_ just now (maybe even twice). Let me know if it worked.

**Comment by fheft** [comment]
Thanks, I was able to join and I'm able to publish now.
